# Generated by Django 3.2.9 on 2021-11-20 09:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectNo', models.CharField(choices=[('PJ1', 'PROJECT1'), ('PJ2', 'PROJECT2'), ('PJ3', 'PROJECT3'), ('PJ4', 'PROJECT4'), ('PJ5', 'PROJECT5')], default='PJ1', max_length=10)),
                ('taskName', models.CharField(max_length=30, unique=True)),
                ('startTime', models.TimeField(default='14:57:47')),
                ('timeTaken', models.CharField(max_length=10)),
                ('endTime', models.TimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
