# Generated by Django 3.2.9 on 2021-11-19 16:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20211119_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='startTime',
            field=models.TimeField(default=datetime.datetime(2021, 11, 19, 16, 44, 3, 792033, tzinfo=utc)),
        ),
    ]
