# Generated by Django 3.2.9 on 2021-11-19 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20211119_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='startTime',
            field=models.TimeField(default='22:54:58'),
        ),
    ]
